[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-submit-async-request",
    "allow-fetch-media",
    "allow-fetch-user-profile",
    "allow-get-devices",
    "allow-verify-device",
    "allow-submit-matrix-login-request",
    "allow-forward-oauth-login-deeplink",
    "allow-build-client-from-homeserver-url",
    "allow-check-homeserver-auth-type",
    "allow-get-dm-room-from-user-id",
    "allow-check-device-verification",
    "allow-has-backup-setup",
    "allow-restore-backup-with-passphrase",
    "allow-setup-new-backup",
    "allow-search-users",
    "allow-disconnect-and-clear-session",
    "allow-check-if-last-device",
    "allow-is-logged-in",
    "allow-reset-cross-signing",
    "allow-edit-user-information",
    "allow-upload-media",
    "allow-filter-room-list",
    "allow-define-room-informations",
    "allow-register-notifications",
]
